# Generated by Django 5.0.2 on 2024-03-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=50, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('nike', 'Nike'), ('jordan', 'Jordan'), ('new balance', 'New balance'), ('adidas', 'Adidas')], default='nike', max_length=50, verbose_name='тип'),
        ),
    ]
